import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Do Nguyen Phuong",
  description: "Generated by create next app",
  openGraph: {
    title: "Do Nguyen Phuong - Developer",
    images: [
      {
        url: "https://res.cloudinary.com/dwsae4gmt/image/upload/v1695312354/Screenshot_2023-09-21_230403_wrf2lx.png",
        width: 800,
        height: 600,
      },
      {
        url: "https://res.cloudinary.com/dwsae4gmt/image/upload/v1695312354/Screenshot_2023-09-21_230403_wrf2lx.png",
        width: 1800,
        height: 1600,
        alt: "My custom alt",
      },
    ],
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body suppressHydrationWarning={true} className={`${inter.className} `}>
        {children}
      </body>
    </html>
  );
}
